export type Property = {id:string;name:string;operation:string;type:string;city:string;zone:string;area:number;construction?:number;price?:number;beds:number;baths:number;features:string[];description:string;instagram?:string;imageCount:number};

export const properties:Property[]=[
  {id:"PROP-001",name:"Casa I",operation:"Venta",type:"Casa",city:"Torreón",zone:"Las Villas",price:38000000,area:1099.2,construction:693,beds:4,baths:4,features:["Amueblada","Terraza","Jardín","Horno de leña","Oficina","Sala de TV","Vestidores","Cuarto de servicio"],description:"Casa lista para habitar, completamente amueblada, diseñada por arquitecta brasileña y equipada con mobiliario italiano.",instagram:"https://www.instagram.com/p/DZp_ApTETYf/",imageCount:14},
  {id:"PROP-002",name:"Casa II",operation:"Venta",type:"Casa",city:"Gómez Palacio, Durango",zone:"La Cava Residencial",price:9950000,area:311,construction:367.7,beds:3,baths:0,features:["Recámara en planta baja","Terraza","Jardín","Lavandería","Mármol","Carpintería especial"],description:"Casa diseñada por Curiel Arquitectos con espacios abiertos, luz natural y acabados de alta calidad.",instagram:"https://www.instagram.com/p/DZ0CUAkgGd-/",imageCount:3},
  {id:"PROP-003",name:"Lote Las Villas del Cardenchal",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas del Cardenchal",price:3060000,area:360,beds:0,baths:0,features:["Frente a área verde","Terraza común","Canchas de pádel","Cancha de fútbol"],description:"Lote de 12 m de frente por 30 m de fondo, frente a una de las áreas verdes de Villa Agaves.",instagram:"https://www.instagram.com/p/DZGfL8SgOMA/",imageCount:1},
  {id:"PROP-004",name:"Casa III",operation:"Venta",type:"Casa",city:"Torreón",zone:"Las Villas",area:0,beds:4,baths:0,features:["Alberca","Terraza","Bar","Gym","Oficina"],description:"Casa amplia y equipada dentro de Las Villas. Precio y superficies disponibles previa solicitud.",instagram:"https://www.instagram.com/p/DagjExgD34z/",imageCount:12},
  {id:"PROP-005",name:"Lote La Gran Vinícola",operation:"Venta",type:"Terreno",city:"Gómez Palacio, Durango",zone:"La Gran Vinícola",price:8821800,area:1131.07,beds:0,baths:0,features:["Lote amplio","Ligera curvatura","Baja densidad"],description:"Lote de grandes dimensiones con forma ligeramente curva, adecuado para un proyecto arquitectónico especial.",instagram:"https://www.instagram.com/p/DZbV_HxgIJ8/",imageCount:1},
  {id:"PROP-006",name:"Penthouses Torre Latitud 25",operation:"Venta",type:"Departamento",city:"Gómez Palacio, Durango",zone:"Torre Latitud 25",area:0,beds:0,baths:0,features:["Terraza","Vistas panorámicas"],description:"Últimos dos penthouses disponibles en un desarrollo diseñado por Landa + Martínez.",instagram:"https://www.instagram.com/p/DZYmfOiAGCK/",imageCount:6},
  {id:"PROP-008",name:"Nave Industrial Centro",operation:"Venta",type:"Industrial",city:"Torreón",zone:"Centro / Avenida Allende",price:19000000,area:3469.7,construction:3469.7,beds:0,baths:0,features:["Área operativa","Oficinas","Baños","Comedor","Acceso logístico"],description:"Nave lista para manufactura, almacenamiento, logística o distribución, sobre una de las principales vialidades de Torreón.",instagram:"https://www.instagram.com/p/DZ_I9xXAPLz/",imageCount:3},
  {id:"PROP-009",name:"Lote Las Villas",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas",price:5700000,area:600,beds:0,baths:0,features:["Vista al área verde","Vecinos a ambos lados"],description:"Lote de 19.41 m de frente y 19.35 m de fondo dentro de una de las primeras etapas de Las Villas.",instagram:"https://www.instagram.com/p/DZsrUxuhdTa/",imageCount:1},
  {id:"PROP-010",name:"Departamento Lativ",operation:"Venta",type:"Departamento",city:"San Pedro Garza García",zone:"Parque Rufino Tamayo",area:102,beds:2,baths:2.5,features:["Alberca","Gym","Rooftop","Ludoteca","Simulador de golf","Área de asadores","Centro culinario","Salón de eventos","Sport bar","Business center","Acceso directo al parque"],description:"Departamento de 102 m² en Lativ, con dos recámaras y acceso a amenidades premium.",imageCount:3},
];

export const propertyImage=(property:Property,index=1)=>`/properties/${property.id}/${String(index).padStart(2,"0")}.jpg`;
