export type Property = {id:string;name:string;operation:string;type:string;city:string;zone:string;area:number;construction?:number;price?:number;beds:number;baths:number;features:string[];description:string;instagram?:string;imageCount:number;planOnly?:boolean};

export const properties:Property[]=[
  {id:"PROP-001",name:"Casa I",operation:"Venta",type:"Casa",city:"Torreón",zone:"Las Villas",price:38000000,area:1099.2,construction:693,beds:4,baths:4,features:["Amueblada","Terraza","Jardín","Horno de leña","Oficina","Sala de TV","Vestidores","Cuarto de servicio"],description:"Casa lista para habitar, completamente amueblada, diseñada por arquitecta brasileña y equipada con mobiliario italiano.",instagram:"https://www.instagram.com/p/DZp_ApTETYf/",imageCount:14},
  {id:"PROP-002",name:"Casa II",operation:"Venta",type:"Casa",city:"Gómez Palacio, Durango",zone:"La Cava Residencial",price:9950000,area:311,construction:367.7,beds:3,baths:0,features:["Recámara en planta baja","Terraza","Jardín","Lavandería","Mármol","Carpintería especial"],description:"Casa diseñada por Curiel Arquitectos con espacios abiertos, luz natural y acabados de alta calidad.",instagram:"https://www.instagram.com/p/DZ0CUAkgGd-/",imageCount:3},
  {id:"PROP-003",name:"Lote Las Villas del Cardenchal",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas del Cardenchal",price:3060000,area:360,beds:0,baths:0,features:["Lote AV-04","Superficie: 360 m²","Frente: 12 m","Fondo: 30 m","Frente a área verde","Terraza común","Canchas de pádel","Cancha de fútbol"],description:"Lote AV-04 de 360 m², con 12 m de frente por 30 m de fondo, frente a una de las áreas verdes de Villa Agaves.",instagram:"https://www.instagram.com/p/DZGfL8SgOMA/",imageCount:2},
  {id:"PROP-004",name:"Casa III",operation:"Venta",type:"Casa",city:"Torreón",zone:"Las Villas",area:0,beds:4,baths:0,features:["Alberca","Terraza","Bar","Gym","Oficina"],description:"Casa amplia y equipada dentro de Las Villas. Precio y superficies disponibles previa solicitud.",instagram:"https://www.instagram.com/p/DagjExgD34z/",imageCount:12},
  {id:"PROP-005",name:"Lote La Gran Vinícola",operation:"Venta",type:"Terreno",city:"Gómez Palacio, Durango",zone:"La Gran Vinícola",price:8821800,area:1131.07,beds:0,baths:0,features:["Lote L-19","Superficie: 1,131.07 m²","Frente curvo: 19.59 m","Contrafrente: 23.51 m","Laterales: 41 m y 53.68 m","Lote amplio","Ligera curvatura","Baja densidad"],description:"Lote L-19 de 1,131.07 m² en Valle de Piemonte, con frente curvo de 19.59 m y dimensiones adecuadas para un proyecto arquitectónico especial.",instagram:"https://www.instagram.com/p/DZbV_HxgIJ8/",imageCount:2},
  {id:"PROP-006",name:"Penthouses Torre Latitud 25",operation:"Venta",type:"Departamento",city:"Gómez Palacio, Durango",zone:"Torre Latitud 25",area:485.85,beds:0,baths:0,features:["Terraza","Vistas panorámicas"],description:"Últimos dos penthouses disponibles en un desarrollo diseñado por Landa + Martínez.",instagram:"https://www.instagram.com/p/DZYmfOiAGCK/",imageCount:6},
  {id:"PROP-008",name:"Nave Industrial Centro",operation:"Venta",type:"Industrial",city:"Torreón",zone:"Centro / Avenida Allende",price:19000000,area:3469.7,construction:3469.7,beds:0,baths:0,features:["Área operativa","Oficinas","Baños","Comedor","Acceso logístico"],description:"Nave lista para manufactura, almacenamiento, logística o distribución, sobre una de las principales vialidades de Torreón.",instagram:"https://www.instagram.com/p/DZ_I9xXAPLz/",imageCount:3},
  {id:"PROP-009",name:"Lote Villa Cóndores",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas",price:5700000,area:600,beds:0,baths:0,features:["Lote CN-32","Superficie: 600 m²","Frente: 19.41 m (11.58 m + 7.83 m)","Contrafrente: 19.35 m","Laterales: 31.82 m y 30.28 m","Vista al área verde","Vecinos a ambos lados"],description:"Lote CN-32 de 600 m² en Villa Cóndores, con 19.41 m de frente sobre Circuito Cóndores Poniente y laterales de 31.82 m y 30.28 m.",instagram:"https://www.instagram.com/p/DZsrUxuhdTa/",imageCount:2},
  {id:"PROP-010",name:"Departamento Lativ",operation:"Venta",type:"Departamento",city:"San Pedro Garza García",zone:"Parque Rufino Tamayo",area:102,beds:2,baths:2.5,features:["Alberca","Gym","Rooftop","Ludoteca","Simulador de golf","Área de asadores","Centro culinario","Salón de eventos","Sport bar","Business center","Acceso directo al parque"],description:"Departamento de 102 m² en Lativ, con dos recámaras y acceso a amenidades premium.",imageCount:3},
  {id:"PROP-011",name:"Lote Villa Libélulas",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas",area:400,beds:0,baths:0,features:["Lote LB-17","Superficie: 400 m²","Frente curvo: 15 m","Contrafrente: 26.10 m (25.98 m + 0.12 m)","Laterales: 23.30 m y 22.11 m","Circuito Libélulas","Forma irregular"],description:"Lote LB-17 de 400 m² en Villa Libélulas, con frente curvo de 15 m sobre Circuito Libélulas y un trazo irregular para un proyecto arquitectónico distintivo.",imageCount:1,planOnly:true},
  {id:"PROP-012",name:"Lote Villa Gorriones",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas",area:1000,beds:0,baths:0,features:["Lote GR-01","Superficie: 1,000 m²","Esquina con doble frente","Circuito Gorriones: 23.64 m + 7.85 m + 25.05 m","Paseo de Las Villas: 9.81 m + 25.04 m","Colindancia con GR-02: 33.64 m"],description:"Lote GR-01 de 1,000 m² en esquina, con amplios frentes hacia Circuito Gorriones y Paseo de Las Villas.",imageCount:1,planOnly:true},
  {id:"PROP-013",name:"Lote Villa Venados",operation:"Venta",type:"Terreno",city:"Torreón",zone:"Las Villas",area:3931.05,beds:0,baths:0,features:["Lote E-09","Superficie: 3,931.05 m²","Dos frentes","Callejón Venados: 9.97 m + 8.35 m + 28.93 m + 10.84 m","Segundo frente: 9.43 m + 34.51 m","Linderos: 98.29 m y 82.27 m","Acceso vehicular","Acceso peatonal","Servicios: agua, drenaje, electricidad y teléfono","Barda de piedra mármol mamposteada: 2.20 m"],description:"Lote E-09 de 3,931.05 m² en Villa Venados, con dos frentes, trazo irregular y propuestas de acceso vehicular y peatonal.",imageCount:1,planOnly:true},
];

export const propertyImage=(property:Property,index=1)=>`/properties/${property.id}/${String(index).padStart(2,"0")}.jpg`;
